### ISSUE TITLE
煦涵说CSS（三）：text-overflow

### ISSUE THREAD

**Issue by zuojj** [zuojj/fedlab#11]
[text-overflow](https://www.w3.org/TR/css-ui-3/#text-overflow) 属性常用来处理文本溢出时剪切文本，常用的取值有 clip 、ellipsis 、inherit; 常见的文本溢出处理 CSS：

```css
.ellipsis {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

## 前置条件
1. 该元素必须为 `display:block` 或者 `display:inline-block` 元素，需要设置宽度来控制文本被溢出。
2. 该元素必须设置 `overflow: hidden | scroll | auto`。
3. 文本溢出方向依赖 `direction: rtl | ltr` 属性。
4. 整行溢出依赖 `white-space: nowrap` 属性。

### clip
默认值，设置该值时文本会被裁切。

```css
.to-clip {
    text-overflow: clip;
}
```

### ellipsis
设置改属性文本溢出时会显示省略号。

```css
.to-ellipsis {
    text-overflow: ellipsis;
}
```
## 自定义字符串
可以给text-overflow 设置溢出自定义字符串，现在只有 Firefox 浏览器支持

```css
.custom {
    text-overflow: "fedlab";
}
```
## 两个属性值
两个属性值语法，左右方向溢出，设置 `text-align: center`， 显示中间部分文本，现在只有Firefox支持。

```css
.double {
    text-overflow: ellipsis ellipsis;
    /* 两边溢出 */
    text-align: center;
}
```

> PS：自定字符串及两个属性值情况，都有被遗弃的风险，在生产环境中慎用，目前只在 firefox 中支持。

## 兼容
* IE8/9浏览器 input[type=text] 元素上无效
* Chrome/IE 浏览器 select 元素上无效
* Opera 浏览器加前缀兼容 `-o-text-overflow`

感谢您的阅读

<div style="margin:5px auto;padding-top:1.2em;padding-bottom:0.6em;">
    <div style="font-size:1em; border-style: solid none none; border-top-width: 1px; border-color: rgb(17, 17, 17); color: rgb(204, 204, 204);"></div>
    <div style="margin-top: -0.7em;text-align:center;line-height:1.4;">
    <span style="padding:8px 23px;background-color:#fff;color:#000;margin-top:-1em;">EOF</span>
    </div>
</div>

<div style="font-size: 12px; color: #8e8e8e">
    <p>作者[煦涵]</p>
    <p>2017年07月08日</p>
</div>

<div style="text-align: center; font-size: 12px; color: #8e8e8e;">
    <div>下面是「FED实验室」的微信公众号二维码，欢迎扫描关注：</div>
    <img src="https://cloud.githubusercontent.com/assets/5378965/26525703/ba3707ac-4392-11e7-8a99-db27837f9c3c.jpg" alt="关注FED实验室" title="关注FED实验室">
</div>
